# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [39]:
import torch


# Create random tensor
x = torch.rand(7, 7)
x, x.shape

(tensor([[0.1872, 0.0340, 0.9442, 0.8802, 0.0012, 0.5936, 0.4158],
         [0.4177, 0.2711, 0.6923, 0.2038, 0.6833, 0.7529, 0.8579],
         [0.6870, 0.0051, 0.1757, 0.7497, 0.6047, 0.1100, 0.2121],
         [0.9704, 0.8369, 0.2820, 0.3742, 0.0237, 0.4910, 0.1235],
         [0.1143, 0.4725, 0.5751, 0.2952, 0.7967, 0.1957, 0.9537],
         [0.8426, 0.0784, 0.3756, 0.5226, 0.5730, 0.6186, 0.6962],
         [0.5300, 0.2560, 0.7366, 0.0204, 0.2036, 0.3748, 0.2564]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [40]:
# Create another random tensor
y = torch.rand(1, 7)

# Perform matrix multiplication
z = torch.matmul(x, y.T)
z, z.shape

(tensor([[1.6083],
         [1.7687],
         [1.0874],
         [1.0720],
         [1.5352],
         [1.7365],
         [0.9310]]),
 torch.Size([7, 1]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [41]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
X = torch.rand(size=(7, 7))
Y = torch.rand(size=(1, 7))

# Matrix multiply tensors
Z = torch.matmul(X, Y.T)
Z, Z.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [42]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [43]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
dev = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
tensor1 = torch.rand(2, 3, device=dev)
tensor2 = torch.rand(2, 3, device=dev)
tensor1, tensor1
# tensor_A = torch.rand(size=(2,3)).to(dev)
# tensor_B = torch.rand(size=(2,3)).to(dev)
# tensor_A, tensor_B


Device: cuda


(tensor([[0.1272, 0.8167, 0.5440],
         [0.6601, 0.2721, 0.9737]], device='cuda:0'),
 tensor([[0.1272, 0.8167, 0.5440],
         [0.6601, 0.2721, 0.9737]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [44]:
# Perform matmul on tensor_A and tensor_B
tensor3 = torch.matmul(tensor1, tensor2.T)
tensor3, tensor3.shape

(tensor([[0.2786, 0.7668],
         [0.7343, 0.6102]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [45]:
# Find max
maxone = torch.max(tensor3)

# Find min
minone = torch.min(tensor3)
maxone, minone

(tensor(0.7668, device='cuda:0'), tensor(0.2786, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [46]:
# Find arg max
arg_max = torch.argmax(tensor3)

# Find arg min
arg_min = torch.argmin(tensor3)
arg_max, arg_min

(tensor(1, device='cuda:0'), tensor(0, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [47]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor4 = torch.rand(1, 1, 1, 10)

# Remove single dimensions
tensor_squeezed = tensor4.squeeze()

# Print out tensors
print(tensor4, tensor4.shape)
print(tensor_squeezed, tensor_squeezed.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
